### PR TITLE
Don't override consoleblank=0 - correct PR #491

### PR DESCRIPTION
**Pull request by dinosore**
Same code, now in correct place.

Sorry I didn't correct PR #491 before it was merged, but I thought it was being ignored.

### CODE REVIEW

**Comment by dinosore** [comment]
Here is the post-install i used to test on Pi 0W in case anyone wants to try on another model. My class 4 sd card is now defunct.

#!/bin/bash

# post-install.txt

echo "Iime now: $(date +%R:%S)"
now="$(date +%s)"
sofar="$((now - REAL_STARTTIME))"
echo "Time taken: $sofar seconds"

need=$((3600 - sofar))
if [ $need > 0 ] ; then
	echo "Waiting another $need seconds"
	sleep "$need"
fi

echo "Iime now: $(date +%R:%S)"
now="$(date +%s)"
sofar="$((now - REAL_STARTTIME))"
echo "Time taken: $sofar seconds"

echo "Waiting 30 minutes to check that the screen is still on"
sleep 1800

echo "Iime now: $(date +%R:%S)"
now="$(date +%s)"
sofar="$((now - REAL_STARTTIME))"
echo "Time taken: $sofar seconds"

and here is the tail of the log
```
=================================================
=== Start executing post-install.txt. ===
Iime now: 15:29:04
Time taken: 1636 seconds
Waiting another 1964 seconds
Iime now: 16:01:48
Time taken: 3600 seconds
Waiting 30 minutes to check that the screen is still on
Iime now: 16:31:48
Time taken: 5400 seconds
=== Finished executing post-install.txt. ===
=================================================
Removing cdebootstrap-helper-rc.d... OK
Saving current time for fake-hwclock...
Installation finished at Mon Oct  2 16:31:48 UTC 2017 and took 90 min 0 sec (5400 seconds)

```

**Comment by Mausy5043** [comment]
PRs and issues are not ignored. Sometimes it just takes long for us to give them the time they need. We're all volunteers with limited time to spare for this project. So, all help is appreciated.

**Comment by Mausy5043** [comment]
Maybe it's the time of day. But, I don't get what the significance is of moving the code down?
I had no problems with it when I ran the installer last weekend.

Could you elaborate?

**Comment by dinosore** [comment]
It's good to have /proc available when looking at /proc/cmdlone

**Comment by dinosore** [comment]
Didn't mean thinking PR ignored to be a complaint, it was more of anexcuse.

**Pull request merged**
