### PR TITLE
Fixed various shellcheck issues

### PR DESCRIPTION
**Pull request by diederikdehaas**
Implemented most suggesting that http://www.shellcheck.net/ indicated.
I left some items unresolved as they're rather debatable, which we of course can do :wink:

### CODE REVIEW

**Comment by diederikdehaas** [comment]
> pushd and popd still not in busybox?

I actually don't know. I had never heard of those commands when I wrote that part of the code.

**Comment by Mausy5043** [comment]
I missed changes related to globbing and word splitting (https://github.com/koalaman/shellcheck/wiki/Sc2086)
But I guess that's one you want to debate? :wink:

**Comment by diederikdehaas** [comment]
Yep, several of them are for counters. Others may have value, but they weren't as clear to me as the ones I already implemented. And you merged :+1:

**Comment by Mausy5043** [comment]
:grin:

**Pull request merged**
