### PR TITLE
Add 'resolvconf' package to 'minimal' preset

### PR DESCRIPTION
**Pull request by kpfleming**
With IPv6 support in place, there can be two dynamic sources of
recursive DNS server information in the system. To handle this,
install the 'resolvconf' package which will coordinate updates.

### CODE REVIEW

**Comment by diederikdehaas** [comment]
Why not (something like) [`rdnssd`](https://packages.debian.org/jessie/rdnssd) and is it possible to make it conditional on when IPv6 is actually used?

**Comment by diederikdehaas** [comment]
I just made a post in #347 which is also relevant to this and I'd appreciate your input on that :smile:

**Comment by kpfleming** [comment]
The full IPv6 patch will add ```rdnssd``` to the package list as well, but only when IPv6 is enabled (and automatic nameserver discovery is requested). We could make the patch only add ```resolvconf``` when IPv6 is enabled, but I was concerned about having no-IPv6 and yes-IPv6 installed systems behave differently and require different configuration after installation (if the user wants to change how nameservers are configured). Since resolvconf is fairly small, and IIRC all shell scripts, it seemed like a safe thing to add.

Without ```resolvconf```, we'd have to create our own method of coordinating between ```isc-dhcp-client``` (for IPv4) and ```rdnssd``` (for IPv6) in the final installed system.

**Comment by diederikdehaas** [comment]
> resolvconf is fairly small, and IIRC all shell scripts

My worry was that it was a running service and would therefor also use RAM. Turns out this is not the case and that relieves me of my main concern.

**Comment by diederikdehaas** [comment]
> The full IPv6 patch

I haven't yet merged your other PRs as I'd like to see it in full.
(and it actually would be easier if they're all in 1 PR)

**Comment by kpfleming** [comment]
Fair enough, I'll get my branch updated against the current master branch, and then send a PR. I'll keep the individual commits so they can be commented on separately if desired.

**Comment by diederikdehaas** [comment]
Excellent, I do like separate commits :+1:

**Pull request closed without merging**
