### PR TITLE
Update README.md typo.

### PR DESCRIPTION
**Pull request by DavisMiculis**
Updated README.md SD card size typo.

### CODE REVIEW

**Comment by diederikdehaas** [comment]
Thanks for the idea :+1: 

But it's actually not a typo. The number came from a 'loose' addition of 128MB for `/boot/` and 512MB for `/` which is needed to install the system. The 64MB is only true for the installer image itself.

**Comment by DavisMiculis** [comment]
Oh, sorry, just somehow while reading it felt like there should be 64 followed by 128. Maybe it just needs more clarification then?

**Comment by diederikdehaas** [comment]
Yeah, that probably wouldn't hurt. I guess I came up with it because of Bill Gates' famous remark :wink:

**Comment by Mausy5043** [comment]
@diederikdehaas Bill thought 640KB should be enough, not 64MB. :wink:

**Comment by diederikdehaas** [comment]
You should at least correct me properly then ... not 640MB :wink: LOL

@Mausy5043 btw: interested in becoming an (official) Collaborator?

**Comment by Mausy5043** [comment]
@diederikdehaas : Thanks for the offer. I need to think about this and have lots of questions. If you're still serious, could you contact me via LinkedIn maybe?

**Comment by diederikdehaas** [comment]
Done :wink:

**Pull request closed without merging**
