### PR TITLE
Fixing documentation

### PR DESCRIPTION
**Pull request by Mausy5043**
* typos
* whitespace (automagically fixed by Atom)
* issue #357
* increased readability of the options descriptions

### CODE REVIEW

**Comment by Mausy5043** [comment]
There are still some issues with the `README.MD` that don't feel right. It would be great if someone who is a native speaker could check for grammar and dutchisms and the like.

**Comment by kpfleming** [comment]
I have some networking-related additions to make as part of the IPv6 work, so I'm happy to do a pass over the whole README.md once this is merged.

**Comment by Mausy5043** [comment]
:+1: thanks

**Comment by diederikdehaas** [comment]
Great @Mausy5043 and thanks in advance @kpfleming :+1: 

> whitespace (automagically fixed by Atom)

Be VERY careful with this! Whitespace in markdown is significant. 
For example 2 whitespaces translate into a break/linefeed.
A quick look at the changes you made here didn't show any formatting breaking, but automatic formatting tools can easily have effects you didn't intend.
At some point I want to transform the documentation from GitHub flavored markdown to pure markdown and then it becomes (even) more significant.

**Comment by Mausy5043** [comment]
> For example 2 whitespaces translate into a break/linefeed.
This I did not know.
Thanks for the heads-up.

**Comment by diederikdehaas** [comment]
I/we had an earlier PR which automatically 'fixed' various space issues ... but that one did have negative consequences :wink:

**Comment by diederikdehaas** [comment]
Thanks @Mausy5043 :+1:

**Pull request merged**
