### PR TITLE
Add dependency to BUILD.md

### PR DESCRIPTION
**Pull request by goranche**
we use bc in buildroot.sh, but it's not installed on a Ubuntu server 15.04 system

### CODE REVIEW

**Comment by diederikdehaas** [comment]
Good catch :+1:

**Comment by goranche** [comment]
> Good catch

simple catch :wink:

**Comment by Mausy5043** [comment]
Just my ignorance, but... :confused: 
What does Ubuntu 15.04 have to do with Raspbian? :open_mouth:

**Comment by Mausy5043** [comment]
Oh wait  it's used as a build machine.. :+1:

**Comment by goranche** [comment]
> it's used as a build machine

yup :wink:

**Pull request merged**
