### PR TITLE
Security suggestion on swap permissions

### PR DESCRIPTION
**Pull request by dragetd**
Suggest removing the read-permissions on swap-file. Without, it was left world-readable, allowing other users to read the swap-file.

### CODE REVIEW

**Comment by diederikdehaas** [comment]
Do you have links as to why this would be needed?
I have never seen something like this, the [Debian wiki doesn't mention it](https://wiki.debian.org/Swap) and afaik the system takes care of its security.

**Comment by dragetd** [comment]
If your /swap is world-readable, a local user can read the file and dump informations… strings, images whatnot. This can expose sensitive informations including key-material.

Simple test:
As a regular user:
> strings /swap
will output various interesting strings.

If this is not in the Debian wiki, it should be added there! :-P I'll talk to some Debian people…

**Comment by goranche** [comment]
it's true that the swap file should be accessible only to root, but I'm not convinced that the installer creates the file this way...

**Comment by goranche** [comment]
but I'll check, just to be sure

**Comment by diederikdehaas** [comment]
It's only in the `README.md` :wink:

**Comment by goranche** [comment]
ah... that would explain why I don't remember seeing anything resembling a swap file

**Comment by diederikdehaas** [comment]
Reopened against `v1.0.x` (#316)

**Pull request closed without merging**
