### PR TITLE
wpa_supplicant correction

### PR DESCRIPTION
**Pull request by Mausy5043**
Attempting to fix issue #349 
Moving the required location of `wpa_supplicant.conf` into the `/bootfs/config/files/...` tree.
This enables the file to be installed automagically on the target system.
At the same time the file can be used by the installer to support WiFi installation.

### CODE REVIEW

**Comment by Mausy5043** [comment]
Also related to issue #44

**Comment by goranche** [comment]
but just placing the file in `config/files/...` will not "automagically" copy the file to the installed system...

**Comment by Mausy5043** [comment]
I know you have to add it to the file list from #394

**Comment by Mausy5043** [comment]
A different approach is required. Closing.

**Comment by Mausy5043** [comment]
Not yet deleting the branch

**Pull request closed without merging**
