### PR TITLE
Update kernel version to 4.4

### PR DESCRIPTION
**Pull request by jpdfri**
New kernel from the Raspbian archive.
Tested on Raspberry Pi 2.
Had to remove some INSTALL_MODULES-lines for modules listed in the built-in file.
I didn't edit CHANGELOG, I thought you'd like to vet the pull request first.

### CODE REVIEW

**Comment by goranche** [comment]
hey... thanks for the PR, but I'd recommend reading the [CONTRIBUTING](https://github.com/debian-pi/raspbian-ua-netinst/blob/master/CONTRIBUTING.md) file first...

One of the things it explains is that PR are always done against the development branches and not the master branch. If would be great if you could add the changes to a branch based off of the v1.0.x branch 😉 

Also, there was a [similar merge](https://github.com/debian-pi/raspbian-ua-netinst/pull/408) on the v1.1.x branch, which is very similar to this one, so you might want to check that out to double check.

**Comment by diederikdehaas** [comment]
> If would be great if you could add the changes to a branch based off of the v1.0.x branch

@goranche do we really want that? :thought_balloon:

**Comment by goranche** [comment]
💭 hm... might be right...

**Comment by jpdfri** [comment]
Ah sorry, went ahead of myself there. However my Pi2 wouldn't boot with the image built from the original scripts with kernel 3.18, I figured that some file created a compatibility issue (say, raspberrypi-bootloader-nokernel, there are 2 of those in the archives now), so 2 birds in one stone...

**Comment by goranche** [comment]
😉   if you're building your own image, start from the v1.1x branch, that should work

closing this PR

**Pull request closed without merging**
