### PR TITLE
Optimizied search for required packages in package list

### PR DESCRIPTION
**Pull request by Zeerix**
Reduces runtime of update.sh from 90s to 30s (on my test machine)
Requires bash 4.x

### CODE REVIEW

**Comment by goranche** [comment]
> Requires bash 4.x

not sure I'm happy with that... it's the reason things were done the way they are...
on the other hand, I don't really have a problem with saying "ok, you need bash 4"... although I would wan't some checks added in this case (would relate to #228 )

**Comment by Zeerix** [comment]
Debian Squeeze and Wheezy already have bash 4. Not sure about Debian Lenny, but that is not in the repository anymore, is it?
But a check would be fine.

**Comment by diederikdehaas** [comment]
I'm fine with requiring bash 4.
On [the GNU Bash homepage](http://tiswww.case.edu/php/chet/bash/bashtop.html#Availability) you can see that it's almost universally available on all platforms, except Solaris < 11 and MinGW but Cygwin does, so it should work on windows too.

(I've heard the installer also gets build on mainframes :stuck_out_tongue_closed_eyes: )

**Comment by Mausy5043** [comment]
> (I've heard the installer also gets build on mainframes :stuck_out_tongue_closed_eyes: )
:wink: 
On the current version of OSX (10.10.3 Yosemite) people have:
```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)
```

On the 'mainframe' I have:
```
$ bash --version
GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)
```

So no worries there, but for OSX users this might be a problem. Apple does not offer an upgrade to bash 4 (yet), so people will have to install a homebrew package called: `brew` to get to bash 4. Not sure if this is desirable.

**Comment by Zeerix** [comment]
So I removed the associative array and executed `time ./update.sh`:

Original: `real    1m23.576s`
Patched: `real    0m32.515s`

**Comment by diederikdehaas** [comment]
Nice :+1: 

(I'll review/test/merge it after the weekend unless @goranche beats me to it)

**Comment by goranche** [comment]
> Anyone with OS X around?

yup :wink: 
(although I'm not building on OS X, too many problems for now, might have a go at changing the scripts some time in the future... but this is not a reason to stick with bash 3)

**Comment by diederikdehaas** [comment]
@Zeerix Can you change the target branch to v1.0.x? 
You should be able to just modify this PR.
I/We will merge it into v1.1.x later on.

**Comment by diederikdehaas** [comment]
Alternatively we can just merge this PR and create a backport for v1.0.x

**Comment by diederikdehaas** [comment]
Thanks for your PR @Zeerix, much appreciated :+1: 

I'll do a backport and submit that as a separate PR

**Pull request merged**
