### PR TITLE
Merge changes from 1.0 into 1.1

### PR DESCRIPTION
**Pull request by diederikdehaas**
The branches were getting rather out of sync, this PR fixes that.

### CODE REVIEW

**Comment by goranche** [comment]
I'll leave this one as "last", so the other changes can be added as well

**Comment by diederikdehaas** [comment]
So you want me to merge the just merged PRs into this one?

**Comment by goranche** [comment]
let's wait for #264 as well :wink:

**Comment by diederikdehaas** [comment]
I think it's better you merge this PR and merge the changes from the latest PRs separately.

**Comment by goranche** [comment]
k

**Pull request merged**
