### PR TITLE
Kernel 4.4 update

### PR DESCRIPTION
**Pull request by diederikdehaas**
Currently you can't build an installer that boots due to incompatibility between the new firmware files and the 3.18 kernel. This PR fixes that.

### CODE REVIEW

**Comment by Mausy5043** [comment]
This change will prevent use of pre-4.x kernels. Is that intended?

**Comment by diederikdehaas** [comment]
Can you clarify what you mean (which change)?

A change/update in the `raspberrypi-bootloader-nokernel` package caused the 3.18 kernel to not boot anymore. So without some workaround to use an older version of that package, you can't use kernel 3.18 anymore. I haven't tested older kernels then 3.18 though.

So it's changes in the archives that may indeed prevent the use of older kernels.
This change just adapts adapts to that. I would have preferred that any old kernel would still be usable, but I fear that it is not possible anymore.

**Comment by Mausy5043** [comment]
I meant ripping out the modules that are built-in into the kernel 4.x

**Comment by Mausy5043** [comment]
I did an install with the current v1.1.x installer this morning and ended up with a system that has:
```
pi@rbian ~ $ uname -a
Linux rbian 4.4.0-1-rpi #1 Debian 4.4.6-1+rpi14 (2016-05-05) armv6l GNU/Linux
```

So, what's up with that then?

**Comment by Mausy5043** [comment]
Oh wait. The installed system gets 4.4.0.  The installer not yet. I get it now

**Comment by diederikdehaas** [comment]
Then yes. Or we make it all conditionally which is probably a bad idea as it's a lot of work for very little gain. At least for the installer kernel, which this PR is about.
But yes, the installed system gets the 4.4 kernel too as the kernel meta package was updated too.
Plugwash didn't intended to do that yet, but did so when I reported him that the 3.18 kernel didn't boot anymore.

I think it is a terrible change by the RPF, which raspbian.org 'inherited'. For some stupid reason they still refuse to use an initramfs and thus change the kernel config at random, causing issues like you see in this PR.

**Comment by Mausy5043** [comment]
Well, my original question was just to make sure that this change is a deliberate move. I don't see a need to question the change itself.

**Comment by diederikdehaas** [comment]
I am not happy that the change is needed, but it is needed for the 4.4 kernel and therefor my code changes were deliberate.

**Comment by Mausy5043** [comment]
:ok:
Not that it matters a lot, but any reason you opted for the 4.4.0 i.s.o. a newer build?

**Comment by diederikdehaas** [comment]
There's a big difference in the version numbering scheme the RPF uses and what Debian/raspbian.org uses. 
The RPF actually doesn't have one apart from \<previous-nr\> + 1, but Debian/Raspbian versions their kernels according to stable ABI. 

Earlier you posted:
`Linux rbian 4.4.0-1-rpi #1 Debian 4.4.6-1+rpi14 (2016-05-05) armv6l GNU/Linux`
Which means it's actually using the 4.4.6 kernel version.

**Comment by diederikdehaas** [comment]
Also: I'm not picking a specific kernel (version) myself, I just use what's made available in the raspbian.org repos.

**Comment by Mausy5043** [comment]
Great job @diederikdehaas. Tanks 👍 .

**Comment by Mausy5043** [comment]
Migrating to newer kernels (which is a good thing) makes it more difficult to downgrade to older kernels. Should we maybe close #166 ?

**Comment by diederikdehaas** [comment]
I agree that you'd likely *want* newer kernels, but I still consider #166 a valid request and it shouldn't actually be too difficult to implement as raspbian.org still has those older kernels in the repo.

**Pull request merged**
