### PR TITLE
Installer options sorted alphabetically

### PR DESCRIPTION
**Pull request by Mausy5043**
Increases readability

### CODE REVIEW

**Comment by diederikdehaas** [comment]
While I agree that the ordering of the config options can/should be improved, I don't think that sorting them alphabetically is the solution.
It's a good idea to figure out how we like to group config options. One group that immediately springs to mind is network, but we should figure out appropriate groups for all of them.

Not closing this PR just yet as it is a useful discussion subject.

**Comment by Mausy5043** [comment]
Agree.

**Comment by Mausy5043** [comment]
I propose to close this PR.
If needed we can open an issue about ordering the options differently.

**Comment by diederikdehaas** [comment]
Agreed :+1:

**Pull request closed without merging**
